# Generated by Django 4.2.3 on 2023-07-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('celular', models.TextField(max_length=20)),
                ('mail', models.TextField(max_length=100)),
                ('mascota', models.TextField(max_length=50)),
                ('comentario', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'promo_table',
            },
        ),
    ]
